'use client'
import React from "react"
import { Download } from "lucide-react"
import { Button } from "@/components/ui/button"

interface DownloadSummaryButtonProps {
    title?: string;
    summary_text?: string;
    createdAt?: string | Date;
    fileName?: string;
}

export default function DownloadSummaryButton({
    title = "Summary",
    summary_text = "",
    createdAt = new Date(),
    fileName = "Unknown file"
}: DownloadSummaryButtonProps) {
    
    const handleDownload = () => {
        const dateStr = new Date(createdAt).toLocaleDateString();
        const summaryContent = `# ${title}
Generated Summary
Generated on: ${dateStr}
Source File: ${fileName}

${summary_text}

Generated by Sommaire AI`;

        const blob = new Blob([summaryContent], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);

        const link = document.createElement('a');
        link.href = url;
        link.download = `Summary-${title.replace(/[^a-z0-9]/gi, '_')}.txt`;
        document.body.appendChild(link);
        link.click();

        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }

    return (
        <Button 
            size='sm' 
            className="h-8 px-3 bg-rose-100 text-rose-600 hover:text-rose-700 hover:bg-rose-50 border border-rose-200" 
            onClick={handleDownload}
        >
            <Download className="h-4 w-4 mr-2" />
            Download Summary
        </Button>
    )
}